import type { Metadata } from "next";

import "@/styles/config.css";
import "@/styles/main.css";
import "@/styles/lenis.css";
import "@/styles/clone.css";
import "@/styles/config_clone.css";


import MainLayout from "@/layouts/MainLayout";
import LoadingPage from "@/components/new/LoadingPage";
export const metadata: Metadata = {
  title: "20 Studio || Creative Fashion || Digital Design",
  description: "Generated by 20 Studio Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body  suppressHydrationWarning={true}>
      <main>
     {/*    <ControlsState/> */}
      <LoadingPage/>
   
      <MainLayout></MainLayout>
      </main>

     
      </body>
    </html>
  );
}
